# Generated by Django 2.1.3 on 2018-11-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.TextField(default=None, null=True),
        ),
    ]
